version: '3'
services:
  spring-boot-app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
  react-app:
    build:
      context: ./ui-bundle/radium-sample
      dockerfile: Dockerfile
    ports:
      - "3000:3000"